#############################
### parameter config file ###
#############################

dataroot: '' # path to dataset
dataname: '' # 'Name of dataset, use together with dataroot to navigate to the dataset
dataset: 
  - cifar10
  - lsun
  - imagenet
  - folder
  - lfw
  - fake
  - step_rate
  - variability
  - pattern
epoch: 25         # Number of epochs to train for
lambda_lp: 0.1    # Penalty for Lipschitz divergence
critic_iters: 5   # How many critic iterations per generator iteration  
batch_size: 256
max_steps: 300
iters: 20000     # How many generator iterations to train for
manualSeed: 123  # set graph-level seed
T: 15.0          # End time of simulation
seq_num: 20000   # Number of sequences
mode: 'wgan-lp'  # Type of Network to use: wgan-lp | dcgan
data: 'hawkes'   # hawkes | selfcorrecting | gaussian| rnn
cuda: 1          # Enables cuda
ngpu: 1          # Number of GPUs to use
gen: ''          # Path to Generator to continue training
disc: ''         # Path to Discriminator to continue training